# docker-compose.yml
version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://backend:4000/api}
    restart: always
    networks:
      - elastic-finance-network
    depends_on:
      - backend
    # Removed the volume mount for node_modules that could cause conflicts

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:3000}
    restart: always
    networks:
      - elastic-finance-network
    volumes:
      - ./docs:/app/docs
    dns:
      - 8.8.8.8  # Google's DNS
      - 1.1.1.1  # Cloudflare's DNS

networks:
  elastic-finance-network:
    driver: bridge