services:
  - type: web
    name: elastic-finance-api
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: https://elastic-finance.vercel.app
      - key: OPENAI_API_KEY
        sync: false
    routes:
      - type: rewrite
        source: /(.*)
        destination: /