name: Deploy to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Prepare backend for Azure Functions
        run: |
          # Create host.json file
          echo '{
            "version": "2.0",
            "extensionBundle": {
              "id": "Microsoft.Azure.Functions.ExtensionBundle",
              "version": "[4.*, 5.0.0)"
            }
          }' > backend/host.json
          
          # Create function.json for HTTP trigger
          mkdir -p backend/api
          echo '{
            "bindings": [
              {
                "authLevel": "anonymous",
                "type": "httpTrigger",
                "direction": "in",
                "name": "req",
                "methods": ["get", "post"],
                "route": "{*path}"
              },
              {
                "type": "http",
                "direction": "out",
                "name": "res"
              }
            ]
          }' > backend/api/function.json
          
          # Create function entry point
          echo 'const app = require("../src/index");
          
          module.exports = async function (context, req) {
            context.log("HTTP trigger function processed a request.");
            
            // Create Express-compatible request/response objects
            context.req.originalUrl = context.req.url || "/";
            context.req.path = context.req.params.path || "/";
            
            // Setup response callback
            const res = {
              status: function(status) {
                context.res = { status };
                return this;
              },
              send: function(body) {
                if (!context.res) context.res = {};
                context.res.body = body;
                return this;
              },
              json: function(body) {
                if (!context.res) context.res = {};
                context.res.headers = { "Content-Type": "application/json" };
                context.res.body = body;
                return this;
              },
              set: function(key, value) {
                if (!context.res) context.res = {};
                if (!context.res.headers) context.res.headers = {};
                context.res.headers[key] = value;
                return this;
              },
              end: function() {
                return this;
              }
            };
            
            // Handle the request with Express app
            try {
              await new Promise((resolve, reject) => {
                app._router.handle(context.req, res, (err) => {
                  if (err) reject(err);
                  else resolve();
                });
              });
            } catch (error) {
              context.log.error("Error processing request:", error);
              context.res = {
                status: 500,
                body: "Internal Server Error"
              };
            }
          };' > backend/api/index.js

      - name: Export Express app
        run: |
          # Add module export to index.js
          echo "// Export the Express app for Azure Functions" >> backend/src/index.js
          echo "module.exports = app;" >> backend/src/index.js
          
      # Create .env file with OpenAI API key
      - name: Create env file
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > backend/.env

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy backend to Azure Functions
        uses: azure/functions-action@v1
        with:
          app-name: 'elastic-finance-api'
          package: 'backend'

      # Add app settings including OpenAI API Key
      - name: Configure Function App Settings
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az functionapp config appsettings set --name elastic-finance-api --resource-group elastic-finance --settings "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" "CORS_ORIGIN=https://elastic-finance.azurestaticapps.net"

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: deploy-backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Create images directory
        run: |
          mkdir -p frontend/public/images/learn

      - name: Generate placeholder images
        run: |
          cd frontend
          node scripts/setup-images.js

      - name: Update next.config.js for static export
        run: |
          cat > frontend/next.config.js << 'EOL'
          /** @type {import('next').NextConfig} */
          const nextConfig = {
            reactStrictMode: true,
            swcMinify: true,
            
            // Set output to 'export' for static site generation
            output: 'export',
            
            // Configure image handling
            images: {
              unoptimized: true,
            },
            
            // Make sure PostCSS plugins are correctly applied
            webpack: (config) => {
              return config;
            },
          }
          
          module.exports = nextConfig
          EOL

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Update API URL
        run: |
          echo "NEXT_PUBLIC_API_URL=https://elastic-finance-api.azurewebsites.net/api" > frontend/.env.production

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      # Login to Azure (repeated for this job)
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy using Azure CLI directly to Static Website in Storage Account
      - name: Create storage account if not exists
        uses: azure/CLI@v1
        with:
          inlineScript: |
            # Check if storage account exists
            if ! az storage account show --name elasticfinance --resource-group elastic-finance &>/dev/null; then
              echo "Creating storage account..."
              az storage account create --name elasticfinance --resource-group elastic-finance --location eastus --sku Standard_LRS --kind StorageV2 --https-only true --min-tls-version TLS1_2 --allow-blob-public-access true
            fi
            
            # Enable static website
            az storage blob service-properties update --account-name elasticfinance --static-website --index-document index.html --404-document 404.html

      # Upload website files
      - name: Upload website files
        uses: azure/CLI@v1
        with:
          inlineScript: |
            # Upload all files from the out directory
            az storage blob upload-batch --account-name elasticfinance --auth-mode login --source frontend/out --destination '$web' --overwrite true

      # Create CDN profile if needed
      - name: Create CDN if not exists
        uses: azure/CLI@v1
        with:
          inlineScript: |
            # Check if CDN profile exists
            if ! az cdn profile show --name elastic-finance-cdn --resource-group elastic-finance &>/dev/null; then
              echo "Creating CDN profile..."
              az cdn profile create --name elastic-finance-cdn --resource-group elastic-finance --sku Standard_Microsoft
            fi
            
            # Check if CDN endpoint exists
            if ! az cdn endpoint show --name elastic-finance --profile-name elastic-finance-cdn --resource-group elastic-finance &>/dev/null; then
              echo "Creating CDN endpoint..."
              # Get storage static website URL
              ORIGIN_URL=$(az storage account show --name elasticfinance --resource-group elastic-finance --query "primaryEndpoints.web" --output tsv | sed 's/https:\/\///' | sed 's/\///')
              
              # Create CDN endpoint
              az cdn endpoint create --name elastic-finance --profile-name elastic-finance-cdn --resource-group elastic-finance --origin $ORIGIN_URL --origin-host-header $ORIGIN_URL --enable-compression true
            fi
            
      - name: Purge CDN endpoint
        uses: azure/CLI@v1
        with:
          inlineScript: |
            # Purge CDN to refresh content
            az cdn endpoint purge --content-paths '/*' --profile-name elastic-finance-cdn --name elastic-finance --resource-group elastic-finance
            
      # Output deployment URL for reference
      - name: Output deployment URLs
        run: |
          echo "Storage static website URL: https://elasticfinance.z13.web.core.windows.net/"
          echo "CDN URL: https://elastic-finance.azureedge.net/"